export const products = [
  {
    id: 65,
    created_at: "2025-04-23T13:19:58.01856+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%2013%20Pro/1.png",
    title: "iPhone 13 Pro",
    category: "smartphones",
    price: 1099.99,
    discountPercentage: 18.3,
    description:
      "The iPhone 13 Pro is a cutting-edge smartphone with a powerful camera system, high-performance chip, and stunning display. It offers advanced features for users who demand top-notch technology.",
    brand: "Apple",
    stock: 26,
    rating: 4.5,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Highly impressed!",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Great product!",
        reviewerName: "Ryan Graham",
        reviewerEmail: "ryan.graham@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 2,
        comment: "Poor quality!",
        reviewerName: "Mason Wright",
        reviewerEmail: "mason.wright@x.dummyjson.com",
      },
      {
        date: "2025-05-05T12:39:05.828Z",
        rating: 5,
        comment: "great mobile",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T12:40:24.638Z",
        rating: 5,
        comment: "great mobile",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T12:41:12.295Z",
        rating: 5,
        comment: "greate mobile",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T12:52:01.407Z",
        rating: 5,
        comment: "test ",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T14:03:30.326Z",
        rating: 5,
        comment: "last test",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T14:04:13.216Z",
        rating: 4,
        comment: "last test",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T14:05:14.967Z",
        rating: 4,
        comment: "dasdasfas",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T17:19:46.230Z",
        rating: 5,
        comment: "great",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 54,
    created_at: "2025-04-23T13:19:57.984618+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20C35/1.png",
    title: "Realme C35",
    category: "smartphones",
    price: 149.99,
    discountPercentage: 16.47,
    description:
      "The Realme C35 is a budget-friendly smartphone with a focus on providing essential features for everyday use. It offers a reliable performance and user-friendly experience.",
    brand: "Realme",
    stock: 81,
    rating: 4.1,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Very happy with my purchase!",
        reviewerName: "Ava Harrison",
        reviewerEmail: "ava.harrison@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 3,
        comment: "Waste of money!",
        reviewerName: "Sophia Brown",
        reviewerEmail: "sophia.brown@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Great product!",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        date: "2025-05-05T15:47:54.289Z",
        rating: 4,
        comment: "great product",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T15:48:36.431Z",
        rating: 4,
        comment: "good product",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T15:49:48.952Z",
        rating: 4,
        comment: "good",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T15:53:55.709Z",
        rating: 4,
        comment: "good product",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T17:20:24.269Z",
        rating: 4,
        comment: "great",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 78,
    created_at: "2025-04-23T13:28:14.25571+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/tablets/iPad%20Mini%202021%20Starlight/1.png",
    title: "iPad Mini 2021 Starlight",
    category: "tablets",
    price: 499.99,
    discountPercentage: 19.48,
    description:
      "The iPad Mini 2021 in Starlight is a compact and powerful tablet from Apple. Featuring a stunning Retina display, powerful A-series chip, and a sleek design, it offers a premium tablet experience.",
    brand: "Apple",
    stock: 32,
    rating: 4.3,
    reviews: [
      {
        date: "2024-05-23T08:56:21.626Z",
        rating: 2,
        comment: "Disappointing product!",
        reviewerName: "Hazel Evans",
        reviewerEmail: "hazel.evans@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.626Z",
        rating: 4,
        comment: "Great product!",
        reviewerName: "Sophia Jones",
        reviewerEmail: "sophia.jones@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.626Z",
        rating: 5,
        comment: "Great product!",
        reviewerName: "Abigail Rivera",
        reviewerEmail: "abigail.rivera@x.dummyjson.com",
      },
      {
        date: "2025-05-05T17:18:09.123Z",
        rating: 4,
        comment: "good product",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T17:19:08.579Z",
        rating: 5,
        comment: "greaaaat",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T17:22:41.562Z",
        rating: 5,
        comment: "good",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T17:23:17.666Z",
        rating: 5,
        comment: "gooood",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-05T17:24:03.842Z",
        rating: 4,
        comment: "last",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
    ],
    categoriesID: 3,
    userID: null,
  },
  {
    id: 79,
    created_at: "2025-04-23T13:28:14.273529+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/tablets/Samsung%20Galaxy%20Tab%20S8%20Plus%20Grey/1.png",
    title: "Samsung Galaxy Tab S8 Plus Grey",
    category: "tablets",
    price: 599.99,
    discountPercentage: 8.11,
    description:
      "The Samsung Galaxy Tab S8 Plus in Grey is a high-performance Android tablet by Samsung. With a large AMOLED display, powerful processor, and S Pen support, it's ideal for productivity and entertainment.",
    brand: "Samsung",
    stock: 76,
    rating: 4.1,
    reviews: [
      {
        date: "2024-05-23T08:56:21.626Z",
        rating: 2,
        comment: "Would not buy again!",
        reviewerName: "Jackson Morales",
        reviewerEmail: "jackson.morales@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.626Z",
        rating: 5,
        comment: "Would buy again!",
        reviewerName: "Cameron Perez",
        reviewerEmail: "cameron.perez@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.626Z",
        rating: 5,
        comment: "Fast shipping!",
        reviewerName: "Nova Cooper",
        reviewerEmail: "nova.cooper@x.dummyjson.com",
      },
      {
        date: "2025-05-07T23:15:02.456Z",
        rating: 4,
        comment: "last",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-07T23:15:17.288Z",
        rating: 4,
        comment: "last",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-07T23:15:53.095Z",
        rating: 4,
        comment: "last",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-07T23:17:46.563Z",
        rating: 4,
        comment: "last",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-12T22:03:06.951Z",
        rating: 5,
        comment: "text",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
    ],
    categoriesID: 3,
    userID: null,
  },
  {
    id: 82,
    created_at: "2025-05-28T16:44:50.661465+00:00",
    image:
      "https://msxxdsxdobsfqyxuvjla.supabase.co/storage/v1/object/public/products-images/0.29172865403303994_Apple-iPhone-16.png",
    title: "iphone 16",
    category: "smartphones",
    price: 999,
    discountPercentage: 0,
    description:
      "Taking photos and videos is faster than ever with the Apple iPhone 16's Camera Control feature. The Quick Access to camera tools lets you open the camera and adjust settings effortlessly.\r\nyou can open the camera with just a single tab, and another tap to capture a photo instantly. Double-tap to switch camera settings, then swipe to adjust them effortlessly.\r\nApple iPhone 16 is more than just a smartphone with a camera. With Visual Intelligence, simply point the camera to instantly explore and learn more about any object around you.",
    brand: "apple",
    stock: 13,
    rating: 0,
    reviews: [],
    categoriesID: 4,
    userID: 5,
  },
  {
    id: 53,
    created_at: "2025-04-23T13:19:57.97702+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Beats%20Flex%20Wireless%20Earphones/1.png",
    title: "Beats Flex Wireless Earphones",
    category: "mobile-accessories",
    price: 49.99,
    discountPercentage: 8.27,
    description:
      "The Beats Flex Wireless Earphones offer a comfortable and versatile audio experience. With magnetic earbuds and up to 12 hours of battery life, they are ideal for everyday use.",
    brand: "Beats",
    stock: 49,
    rating: 4.17,
    reviews: [
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Very satisfied!",
        reviewerName: "Hannah Robinson",
        reviewerEmail: "hannah.robinson@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 4,
        comment: "Awesome product!",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Very satisfied!",
        reviewerName: "Grayson Coleman",
        reviewerEmail: "grayson.coleman@x.dummyjson.com",
      },
    ],
    categoriesID: 5,
    userID: null,
  },
  {
    id: 50,
    created_at: "2025-04-23T13:19:57.960754+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/iPhone%20X/1.png",
    title: "iPhone X",
    category: "smartphones",
    price: 899.99,
    discountPercentage: 14.19,
    description:
      "The iPhone X is a flagship smartphone featuring a bezel-less OLED display, facial recognition technology (Face ID), and impressive performance. It represents a milestone in iPhone design and innovation.",
    brand: "Apple",
    stock: 99,
    rating: 4.96,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 1,
        comment: "Very unhappy with my purchase!",
        reviewerName: "Eleanor Tyler",
        reviewerEmail: "eleanor.tyler@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Very satisfied!",
        reviewerName: "Maya Reed",
        reviewerEmail: "maya.reed@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Fast shipping!",
        reviewerName: "Elena Baker",
        reviewerEmail: "elena.baker@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 61,
    created_at: "2025-04-23T13:19:58.002734+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20MagSafe%20Battery%20Pack/1.png",
    title: "Apple MagSafe Battery Pack",
    category: "mobile-accessories",
    price: 99.99,
    discountPercentage: 10.27,
    description:
      "The Apple MagSafe Battery Pack is a portable and convenient way to add extra battery life to your MagSafe-compatible iPhone. Attach it magnetically for a secure connection.",
    brand: "Apple",
    stock: 80,
    rating: 2.61,
    reviews: [
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Very pleased!",
        reviewerName: "Hazel Gardner",
        reviewerEmail: "hazel.gardner@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Very satisfied!",
        reviewerName: "Aurora Rodriguez",
        reviewerEmail: "aurora.rodriguez@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Very pleased!",
        reviewerName: "Victoria McDonald",
        reviewerEmail: "victoria.mcdonald@x.dummyjson.com",
      },
    ],
    categoriesID: 5,
    userID: null,
  },
  {
    id: 48,
    created_at: "2025-04-23T13:19:57.933974+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20X21/1.png",
    title: "Vivo X21",
    category: "smartphones",
    price: 499.99,
    discountPercentage: 7.32,
    description:
      "The Vivo X21 is a premium smartphone with a focus on cutting-edge technology. It features an in-display fingerprint sensor, a high-resolution display, and advanced camera capabilities.",
    brand: "Vivo",
    stock: 0,
    rating: 2.75,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Highly recommended!",
        reviewerName: "Logan Lee",
        reviewerEmail: "logan.lee@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Highly recommended!",
        reviewerName: "Nolan Gonzalez",
        reviewerEmail: "nolan.gonzalez@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Fast shipping!",
        reviewerName: "Bella Grant",
        reviewerEmail: "bella.grant@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 49,
    created_at: "2025-04-23T13:19:57.953837+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Stick%20Monopod/1.png",
    title: "Selfie Stick Monopod",
    category: "mobile-accessories",
    price: 12.99,
    discountPercentage: 15.29,
    description:
      "The Selfie Stick Monopod is a extendable and foldable device for capturing the perfect selfie or group photo. Compatible with smartphones and cameras.",
    brand: "SnapTech",
    stock: 33,
    rating: 2.93,
    reviews: [
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Great product!",
        reviewerName: "Aaron Cook",
        reviewerEmail: "aaron.cook@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 4,
        comment: "Very happy with my purchase!",
        reviewerName: "Emma Wilson",
        reviewerEmail: "emma.wilson@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 1,
        comment: "Would not recommend!",
        reviewerName: "Mia Miller",
        reviewerEmail: "mia.miller@x.dummyjson.com",
      },
    ],
    categoriesID: 5,
    userID: null,
  },
  {
    id: 59,
    created_at: "2025-04-23T13:19:58.002862+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20X/1.png",
    title: "Realme X",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 2.39,
    description:
      "The Realme X is a mid-range smartphone known for its sleek design and impressive display. It offers a good balance of performance and camera capabilities for users seeking a quality device.",
    brand: "Realme",
    stock: 87,
    rating: 4.2,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Highly recommended!",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Very satisfied!",
        reviewerName: "Madison Collins",
        reviewerEmail: "madison.collins@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Fast shipping!",
        reviewerName: "Emily Johnson",
        reviewerEmail: "emily.johnson@x.dummyjson.com",
      },
      {
        date: "2025-05-12T21:53:28.158Z",
        rating: 4,
        comment: "hallo",
        reviewerName: "aly salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-12T21:58:06.218Z",
        rating: 4,
        comment: "test",
        reviewerName: "aly salah",
        reviewerEmail: "test@gamil.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 69,
    created_at: "2025-04-23T13:19:58.064937+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20F19%20Pro%20Plus/1.png",
    title: "Oppo F19 Pro Plus",
    category: "smartphones",
    price: 399.99,
    discountPercentage: 15.62,
    description:
      "The Oppo F19 Pro Plus is a feature-rich smartphone with a focus on camera capabilities. It boasts advanced photography features and a powerful performance for a premium user experience.",
    brand: "Oppo",
    stock: 92,
    rating: 2.57,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Would buy again!",
        reviewerName: "Benjamin Foster",
        reviewerEmail: "benjamin.foster@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Very pleased!",
        reviewerName: "Lillian Bishop",
        reviewerEmail: "lillian.bishop@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 3,
        comment: "Would not recommend!",
        reviewerName: "Harper Garcia",
        reviewerEmail: "harper.garcia@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 51,
    created_at: "2025-04-24T13:19:57.973198+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20AirPods%20Max%20Silver/1.png",
    title: "Apple AirPods Max Silver",
    category: "mobile-accessories",
    price: 549.99,
    discountPercentage: 11.7,
    description:
      "The Apple AirPods Max in Silver are premium over-ear headphones with high-fidelity audio, adaptive EQ, and active noise cancellation. Experience immersive sound in style.",
    brand: "Apple",
    stock: 7,
    rating: 3.11,
    reviews: [
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 1,
        comment: "Waste of money!",
        reviewerName: "Harper Kelly",
        reviewerEmail: "harper.kelly@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 3,
        comment: "Not as described!",
        reviewerName: "Abigail Rivera",
        reviewerEmail: "abigail.rivera@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Excellent quality!",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
    ],
    categoriesID: 5,
    userID: null,
  },
  {
    id: 52,
    created_at: "2025-04-23T13:19:57.974721+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Selfie%20Lamp%20with%20iPhone/1.png",
    title: "Selfie Lamp with iPhone",
    category: "mobile-accessories",
    price: 14.99,
    discountPercentage: 13.86,
    description:
      "The Selfie Lamp with iPhone is a portable and adjustable LED light designed to enhance your selfies and video calls. Attach it to your iPhone for well-lit photos.",
    brand: "GadgetMaster",
    stock: 89,
    rating: 2.84,
    reviews: [
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Very happy with my purchase!",
        reviewerName: "Hannah Howard",
        reviewerEmail: "hannah.howard@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Excellent quality!",
        reviewerName: "William Gonzalez",
        reviewerEmail: "william.gonzalez@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 3,
        comment: "Would not buy again!",
        reviewerName: "Amelia Perez",
        reviewerEmail: "amelia.perez@x.dummyjson.com",
      },
    ],
    categoriesID: 5,
    userID: null,
  },
  {
    id: 60,
    created_at: "2025-04-23T13:19:58.003277+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S7/1.png",
    title: "Samsung Galaxy S7",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 8.83,
    description:
      "The Samsung Galaxy S7 is a flagship smartphone known for its sleek design and advanced features. It features a high-resolution display, powerful camera, and robust performance.",
    brand: "Samsung",
    stock: 55,
    rating: 4.9,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Would buy again!",
        reviewerName: "Jace Smith",
        reviewerEmail: "jace.smith@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Would buy again!",
        reviewerName: "Ruby Andrews",
        reviewerEmail: "ruby.andrews@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Great value for money!",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 68,
    created_at: "2025-04-23T13:19:58.061427+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20K1/1.png",
    title: "Oppo K1",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 14.58,
    description:
      "The Oppo K1 series offers a range of smartphones with various features and specifications. Known for their stylish design and reliable performance, the Oppo K1 series caters to diverse user preferences.",
    brand: "Oppo",
    stock: 61,
    rating: 3.39,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 2,
        comment: "Would not buy again!",
        reviewerName: "Penelope Harper",
        reviewerEmail: "penelope.harper@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Very satisfied!",
        reviewerName: "Nathan Reed",
        reviewerEmail: "nathan.reed@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Very happy with my purchase!",
        reviewerName: "Madison Stewart",
        reviewerEmail: "madison.stewart@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 55,
    created_at: "2025-04-23T13:19:57.986865+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Oppo%20A57/1.png",
    title: "Oppo A57",
    category: "smartphones",
    price: 249.99,
    discountPercentage: 12.17,
    description:
      "The Oppo A57 is a mid-range smartphone known for its sleek design and capable features. It offers a balance of performance and affordability, making it a popular choice.",
    brand: "Oppo",
    stock: 76,
    rating: 3.1,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 2,
        comment: "Not worth the price!",
        reviewerName: "Owen Fisher",
        reviewerEmail: "owen.fisher@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Fast shipping!",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 2,
        comment: "Very dissatisfied!",
        reviewerName: "Nora Mills",
        reviewerEmail: "nora.mills@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 64,
    created_at: "2025-04-23T13:19:58.020442+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S8/1.png",
    title: "Samsung Galaxy S8",
    category: "smartphones",
    price: 499.99,
    discountPercentage: 2.69,
    description:
      "The Samsung Galaxy S8 is a premium smartphone with an Infinity Display, offering a stunning visual experience. It boasts advanced camera capabilities and cutting-edge technology.",
    brand: "Samsung",
    stock: 75,
    rating: 3.69,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 2,
        comment: "Very unhappy with my purchase!",
        reviewerName: "Christopher West",
        reviewerEmail: "christopher.west@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Very happy with my purchase!",
        reviewerName: "Hazel Evans",
        reviewerEmail: "hazel.evans@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Very happy with my purchase!",
        reviewerName: "Luna Russell",
        reviewerEmail: "luna.russell@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 57,
    created_at: "2025-04-23T13:19:57.993359+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/Apple%20iPhone%20Charger/1.png",
    title: "Apple iPhone Charger",
    category: "mobile-accessories",
    price: 19.99,
    discountPercentage: 1.01,
    description:
      "The Apple iPhone Charger is a high-quality charger designed for fast and efficient charging of your iPhone. Ensure your device stays powered up and ready to go.",
    brand: "Apple",
    stock: 4,
    rating: 3.03,
    reviews: [
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Very satisfied!",
        reviewerName: "Emily Johnson",
        reviewerEmail: "emily.johnson@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 4,
        comment: "Very pleased!",
        reviewerName: "Charlotte Lopez",
        reviewerEmail: "charlotte.lopez@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 5,
        comment: "Highly recommended!",
        reviewerName: "Cameron Perez",
        reviewerEmail: "cameron.perez@x.dummyjson.com",
      },
    ],
    categoriesID: 5,
    userID: null,
  },
  {
    id: 66,
    created_at: "2025-04-23T13:19:58.022894+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20V9/1.png",
    title: "Vivo V9",
    category: "smartphones",
    price: 299.99,
    discountPercentage: 14.57,
    description:
      "The Vivo V9 is a smartphone known for its sleek design and emphasis on capturing high-quality selfies. It features a notch display, dual-camera setup, and a modern design.",
    brand: "Vivo",
    stock: 19,
    rating: 3.1,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 3,
        comment: "Would not recommend!",
        reviewerName: "Elijah Stewart",
        reviewerEmail: "elijah.stewart@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Great product!",
        reviewerName: "Aria Roberts",
        reviewerEmail: "aria.roberts@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Very happy with my purchase!",
        reviewerName: "Hannah Howard",
        reviewerEmail: "hannah.howard@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 58,
    created_at: "2025-04-23T13:19:57.982425+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/mobile-accessories/iPhone%2012%20Silicone%20Case%20with%20MagSafe%20Plum/1.png",
    title: "iPhone 12 Silicone Case with MagSafe Plum",
    category: "mobile-accessories",
    price: 29.99,
    discountPercentage: 14.35,
    description:
      "The iPhone 12 Silicone Case with MagSafe in Plum is a stylish and protective case designed for the iPhone 12. It features MagSafe technology for easy attachment of accessories.",
    brand: "Apple",
    stock: 51,
    rating: 4.41,
    reviews: [
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 1,
        comment: "Very disappointed!",
        reviewerName: "Isaac Lawrence",
        reviewerEmail: "isaac.lawrence@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 1,
        comment: "Would not recommend!",
        reviewerName: "Emily Johnson",
        reviewerEmail: "emily.johnson@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.624Z",
        rating: 4,
        comment: "Highly recommended!",
        reviewerName: "Mateo Bennett",
        reviewerEmail: "mateo.bennett@x.dummyjson.com",
      },
    ],
    categoriesID: 5,
    userID: null,
  },
  {
    id: 67,
    created_at: "2025-04-23T13:19:58.030194+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Samsung%20Galaxy%20S10/1.png",
    title: "Samsung Galaxy S10",
    category: "smartphones",
    price: 699.99,
    discountPercentage: 0.97,
    description:
      "The Samsung Galaxy S10 is a flagship device featuring a dynamic AMOLED display, versatile camera system, and powerful performance. It represents innovation and excellence in smartphone technology.",
    brand: "Samsung",
    stock: 40,
    rating: 2.81,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Great value for money!",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Highly impressed!",
        reviewerName: "Elijah Hill",
        reviewerEmail: "elijah.hill@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 4,
        comment: "Would buy again!",
        reviewerName: "Eleanor Tyler",
        reviewerEmail: "eleanor.tyler@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 62,
    created_at: "2025-04-23T13:19:58.010377+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Vivo%20S1/1.png",
    title: "Vivo S1",
    category: "smartphones",
    price: 249.99,
    discountPercentage: 4.25,
    description:
      "The Vivo S1 is a stylish and mid-range smartphone offering a blend of design and performance. It features a vibrant display, capable camera system, and reliable functionality.",
    brand: "Vivo",
    stock: 13,
    rating: 2.83,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Very pleased!",
        reviewerName: "Alice Smith",
        reviewerEmail: "alice.smith@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Great value for money!",
        reviewerName: "Harper Kelly",
        reviewerEmail: "harper.kelly@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Great product!",
        reviewerName: "Lillian Simmons",
        reviewerEmail: "lillian.simmons@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 63,
    created_at: "2025-04-23T13:19:58.010504+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/smartphones/Realme%20XT/1.png",
    title: "Realme XT",
    category: "smartphones",
    price: 349.99,
    discountPercentage: 3.03,
    description:
      "The Realme XT is a feature-rich smartphone with a focus on camera technology. It comes equipped with advanced camera sensors, delivering high-quality photos and videos for photography enthusiasts.",
    brand: "Realme",
    stock: 53,
    rating: 4.14,
    reviews: [
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 5,
        comment: "Awesome product!",
        reviewerName: "Hannah Howard",
        reviewerEmail: "hannah.howard@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 1,
        comment: "Would not recommend!",
        reviewerName: "Claire Foster",
        reviewerEmail: "claire.foster@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.625Z",
        rating: 1,
        comment: "Very dissatisfied!",
        reviewerName: "Nora Russell",
        reviewerEmail: "nora.russell@x.dummyjson.com",
      },
    ],
    categoriesID: 4,
    userID: null,
  },
  {
    id: 71,
    created_at: "2025-04-23T13:26:46.970662+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/laptops/Huawei%20Matebook%20X%20Pro/1.png",
    title: "Huawei Matebook X Pro",
    category: "laptops",
    price: 1399.99,
    discountPercentage: 15.25,
    description:
      "The Huawei Matebook X Pro is a slim and stylish laptop with a high-resolution touchscreen display, offering a premium experience for users on the go.",
    brand: "Huawei",
    stock: 34,
    rating: 4.62,
    reviews: [
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 4,
        comment: "Great value for money!",
        reviewerName: "Samantha Howard",
        reviewerEmail: "samantha.howard@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 2,
        comment: "Would not buy again!",
        reviewerName: "Daniel Cook",
        reviewerEmail: "daniel.cook@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 5,
        comment: "Very satisfied!",
        reviewerName: "Brayden Fleming",
        reviewerEmail: "brayden.fleming@x.dummyjson.com",
      },
    ],
    categoriesID: 7,
    userID: null,
  },
  {
    id: 72,
    created_at: "2025-04-23T13:26:46.978588+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/laptops/Apple%20MacBook%20Pro%2014%20Inch%20Space%20Grey/1.png",
    title: "Apple MacBook Pro 14 Inch Space Grey",
    category: "laptops",
    price: 1999.99,
    discountPercentage: 9.25,
    description:
      "The MacBook Pro 14 Inch in Space Grey is a powerful and sleek laptop, featuring Apple's M1 Pro chip for exceptional performance and a stunning Retina display.",
    brand: "Apple",
    stock: 39,
    rating: 3.13,
    reviews: [
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 5,
        comment: "Would buy again!",
        reviewerName: "Hunter Gordon",
        reviewerEmail: "hunter.gordon@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 5,
        comment: "Would buy again!",
        reviewerName: "Emma Wilson",
        reviewerEmail: "emma.wilson@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 5,
        comment: "Very pleased!",
        reviewerName: "David Martinez",
        reviewerEmail: "david.martinez@x.dummyjson.com",
      },
    ],
    categoriesID: 7,
    userID: null,
  },
  {
    id: 73,
    created_at: "2025-04-23T13:26:47.085779+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/laptops/Asus%20Zenbook%20Pro%20Dual%20Screen%20Laptop/1.png",
    title: "Asus Zenbook Pro Dual Screen Laptop",
    category: "laptops",
    price: 1799.99,
    discountPercentage: 9.21,
    description:
      "The Asus Zenbook Pro Dual Screen Laptop is a high-performance device with dual screens, providing productivity and versatility for creative professionals.",
    brand: "Asus",
    stock: 38,
    rating: 3.14,
    reviews: [
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 5,
        comment: "Very satisfied!",
        reviewerName: "Jack Ward",
        reviewerEmail: "jack.ward@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 1,
        comment: "Very disappointed!",
        reviewerName: "Ava Harris",
        reviewerEmail: "ava.harris@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.622Z",
        rating: 5,
        comment: "Great value for money!",
        reviewerName: "Brayden Fleming",
        reviewerEmail: "brayden.fleming@x.dummyjson.com",
      },
    ],
    categoriesID: 7,
    userID: null,
  },
  {
    id: 74,
    created_at: "2025-04-23T13:26:47.09407+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/laptops/New%20DELL%20XPS%2013%209300%20Laptop/1.png",
    title: "New DELL XPS 13 9300 Laptop",
    category: "laptops",
    price: 1499.99,
    discountPercentage: 11.7,
    description:
      "The New DELL XPS 13 9300 Laptop is a compact and powerful device, featuring a virtually borderless InfinityEdge display and high-end performance for various tasks.",
    brand: "Dell",
    stock: 18,
    rating: 2.98,
    reviews: [
      {
        date: "2024-05-23T08:56:21.623Z",
        rating: 3,
        comment: "Very disappointed!",
        reviewerName: "Julian Newton",
        reviewerEmail: "julian.newton@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.623Z",
        rating: 4,
        comment: "Very pleased!",
        reviewerName: "Grace Perry",
        reviewerEmail: "grace.perry@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.623Z",
        rating: 5,
        comment: "Great product!",
        reviewerName: "Daniel Taylor",
        reviewerEmail: "daniel.taylor@x.dummyjson.com",
      },
    ],
    categoriesID: 7,
    userID: null,
  },
  {
    id: 77,
    created_at: "2025-04-23T13:28:14.191587+00:00",
    image:
      "https://cdn.dummyjson.com/products/images/laptops/Lenovo%20Yoga%20920/1.png",
    title: "Lenovo Yoga 920",
    category: "laptops",
    price: 1099.99,
    discountPercentage: 7.77,
    description:
      "The Lenovo Yoga 920 is a 2-in-1 convertible laptop with a flexible hinge, allowing you to use it as a laptop or tablet, offering versatility and portability.",
    brand: "Lenovo",
    stock: 71,
    rating: 4,
    reviews: [
      {
        date: "2024-05-23T08:56:21.623Z",
        rating: 4,
        comment: "Very happy with my purchase!",
        reviewerName: "Paisley Bell",
        reviewerEmail: "paisley.bell@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.623Z",
        rating: 4,
        comment: "Very pleased!",
        reviewerName: "Lincoln Kelly",
        reviewerEmail: "lincoln.kelly@x.dummyjson.com",
      },
      {
        date: "2024-05-23T08:56:21.623Z",
        rating: 4,
        comment: "Great product!",
        reviewerName: "Luna Russell",
        reviewerEmail: "luna.russell@x.dummyjson.com",
      },
      {
        date: "2025-05-12T21:49:31.100Z",
        rating: 4,
        comment: "hello",
        reviewerName: "Aly Salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
      {
        date: "2025-05-12T21:53:01.851Z",
        rating: 4,
        comment: "hallo",
        reviewerName: "Aly Salah",
        reviewerEmail: "alysalah83@gmail.com",
      },
    ],
    categoriesID: 7,
    userID: null,
  },
];

export const category = [
  {
    id: 2,
    created_at: "2025-04-25T12:04:14.841929+00:00",
    category: "tv",
    image:
      "https://msxxdsxdobsfqyxuvjla.supabase.co/storage/v1/object/public/categories//tv.png",
  },
  {
    id: 3,
    created_at: "2025-04-25T12:04:40.41179+00:00",
    category: "tablets",
    image:
      "https://msxxdsxdobsfqyxuvjla.supabase.co/storage/v1/object/public/categories//tablet.png",
  },
  {
    id: 7,
    created_at: "2025-04-25T12:59:19.907238+00:00",
    category: "laptops",
    image:
      "https://msxxdsxdobsfqyxuvjla.supabase.co/storage/v1/object/public/categories//laptop.png",
  },
  {
    id: 4,
    created_at: "2025-04-25T12:05:11.125191+00:00",
    category: "smartphones",
    image:
      "https://msxxdsxdobsfqyxuvjla.supabase.co/storage/v1/object/public/categories//smartphone.png",
  },
  {
    id: 1,
    created_at: "2025-04-25T11:58:22.938127+00:00",
    category: "games",
    image:
      "https://msxxdsxdobsfqyxuvjla.supabase.co/storage/v1/object/public/categories//games.png",
  },
  {
    id: 6,
    created_at: "2025-04-25T12:06:38.099597+00:00",
    category: "home-applications",
    image:
      "https://msxxdsxdobsfqyxuvjla.supabase.co/storage/v1/object/public/categories//home-applications.png",
  },
  {
    id: 5,
    created_at: "2025-04-25T12:05:34.00201+00:00",
    category: "mobile-accessories",
    image:
      "https://msxxdsxdobsfqyxuvjla.supabase.co/storage/v1/object/public/categories//mobileAccessories.webp",
  },
];
